//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;

namespace pmc
{
    /// <summary>
    /// 检前问卷表
    /// </summary>
    [JsonObject(MemberSerialization.OptIn), Table(Name = "brprequestionnaire", DisableSyncStructure = true)]
    public partial class brprequestionnaire
    {
        /// <summary>
        /// 主键ID
        /// </summary>
        [JsonProperty, Column(Name = "id", IsPrimary = true, IsIdentity = true)]
        public long id { get; set; }

        /// <summary>
        /// 姓名
        /// </summary>
        [JsonProperty, Column(Name = "name", StringLength = 50)]
        public string name { get; set; }

        /// <summary>
        /// 民族
        /// </summary>
        [JsonProperty, Column(Name = "nation", StringLength = 50)]
        public string nation { get; set; }

        /// <summary>
        /// 性别
        /// </summary>
        [JsonProperty, Column(Name = "gender", StringLength = 10)]
        public string gender { get; set; }

        /// <summary>
        /// 出生日期
        /// </summary>
        [JsonProperty, Column(Name = "birth_date", StringLength = 20)]
        public string birth_date { get; set; }

        /// <summary>
        /// 婚姻状况
        /// </summary>
        [JsonProperty, Column(Name = "marital_status", StringLength = 20)]
        public string marital_status { get; set; }

        /// <summary>
        /// 父母或兄弟姐妹疾病史（可多选）
        /// </summary>
        [JsonProperty, Column(Name = "family_disease_history", StringLength = 1000)]
        public string family_disease_history { get; set; }

        /// <summary>
        /// 父母或兄弟姐妹恶性肿瘤史（可多选）
        /// </summary>
        [JsonProperty, Column(Name = "family_cancer_history", StringLength = 1000)]
        public string family_cancer_history { get; set; }

        /// <summary>
        /// 个人疾病或异常史（可多选）
        /// </summary>
        [JsonProperty, Column(Name = "personal_disease_history", StringLength = 1000)]
        public string personal_disease_history { get; set; }

        /// <summary>
        /// 手术史
        /// </summary>
        [JsonProperty, Column(Name = "surgery_history", StringLength = 1000)]
        public string surgery_history { get; set; }

        /// <summary>
        /// 输血史
        /// </summary>
        [JsonProperty, Column(Name = "blood_transfusion_history", StringLength = 1000)]
        public string blood_transfusion_history { get; set; }

        /// <summary>
        /// 传染病史
        /// </summary>
        [JsonProperty, Column(Name = "infectious_disease_history", StringLength = 1000)]
        public string infectious_disease_history { get; set; }

        /// <summary>
        /// 既往恶性肿瘤史（可多选）
        /// </summary>
        [JsonProperty, Column(Name = "personal_cancer_history", StringLength = 1000)]
        public string personal_cancer_history { get; set; }

        /// <summary>
        /// 职业
        /// </summary>
        [JsonProperty, Column(Name = "occupation", StringLength = 100)]
        public string occupation { get; set; }

        /// <summary>
        /// 体检情况
        /// </summary>
        [JsonProperty, Column(Name = "physical_exam_situation", StringLength = 1000)]
        public string physical_exam_situation { get; set; }

        /// <summary>
        /// 过敏史
        /// </summary>
        [JsonProperty, Column(Name = "allergy_history", StringLength = 1000)]
        public string allergy_history { get; set; }

        /// <summary>
        /// 用户openid
        /// </summary>
        [JsonProperty, Column(Name = "openid", StringLength = 100)]
        public string openid { get; set; }

        /// <summary>
        /// 记录状态（99代表删除）
        /// </summary>
        [JsonProperty, Column(Name = "ifcheck")]
        public int ifcheck { get; set; } = 0;

        /// <summary>
        /// 添加时间
        /// </summary>
        [JsonProperty, Column(Name = "addtime", DbType = "datetime")]
        public DateTime? addtime { get; set; }

        /// <summary>
        /// 更新时间
        /// </summary>
        [JsonProperty, Column(Name = "updatetime", DbType = "datetime")]
        public DateTime? updatetime { get; set; }
    }
}